import Database from 'better-sqlite3';
import fs from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import type { MonitorConfig } from './config.js';
import type { CheckResult } from './check.js';
import type { DomainResult } from './domain.js';

export type State = 'UP' | 'DOWN';
export interface MonitorRow extends MonitorConfig { state: State; outageStarted: number | null; consecutiveFailures: number; createdAt: number; sslValid: boolean | null; sslExpiresAt: number | null; sslDaysRemaining: number | null; domainExpirationDate: number | null; domainDaysRemaining: number | null; warningAlerted: boolean; maintenance: boolean; slowAlerted: boolean; sslAlerted: boolean; heartbeatToken?: string; lastHeartbeatAt: number | null; }
export interface Incident { id: number; monitorId: string; startedAt: number; recoveredAt: number | null; duration: number | null; error: string | null }
export function openDatabase(filename: string): Database.Database {
  const dir = path.dirname(filename); if (dir !== '.') fs.mkdirSync(dir, { recursive: true });
  const db = new Database(filename); db.pragma('journal_mode = WAL');
  db.exec('CREATE TABLE IF NOT EXISTS notification_history (id INTEGER PRIMARY KEY AUTOINCREMENT, monitor_id TEXT NOT NULL, incident_id INTEGER, event_type TEXT NOT NULL, provider TEXT NOT NULL, sent_at INTEGER NOT NULL, success INTEGER NOT NULL, error TEXT, FOREIGN KEY(monitor_id) REFERENCES monitors(id))');
  db.exec(`CREATE TABLE IF NOT EXISTS monitors (id TEXT PRIMARY KEY, name TEXT NOT NULL, url TEXT NOT NULL, monitor_type TEXT NOT NULL DEFAULT 'http', group_name TEXT, heartbeat_token TEXT UNIQUE, expected_interval INTEGER, grace_period INTEGER, last_heartbeat_at INTEGER, interval INTEGER NOT NULL, timeout INTEGER NOT NULL, expected_status INTEGER NOT NULL, keyword TEXT, max_latency INTEGER, method TEXT NOT NULL DEFAULT 'GET', headers_json TEXT, body TEXT, json_path TEXT, json_expected TEXT, active INTEGER NOT NULL DEFAULT 1, maintenance INTEGER NOT NULL DEFAULT 0, slow_alerted INTEGER NOT NULL DEFAULT 0, ssl_alerted INTEGER NOT NULL DEFAULT 0, state TEXT NOT NULL DEFAULT 'UP', outage_started INTEGER, consecutive_failures INTEGER NOT NULL DEFAULT 0, ssl_valid INTEGER, ssl_expires_at INTEGER, ssl_days_remaining INTEGER, created_at INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS checks (id INTEGER PRIMARY KEY AUTOINCREMENT, monitor_id TEXT NOT NULL, timestamp INTEGER NOT NULL, status TEXT NOT NULL, latency INTEGER NOT NULL, slow INTEGER NOT NULL DEFAULT 0, error TEXT, FOREIGN KEY(monitor_id) REFERENCES monitors(id)); CREATE TABLE IF NOT EXISTS incidents (id INTEGER PRIMARY KEY AUTOINCREMENT, monitor_id TEXT NOT NULL, started_at INTEGER NOT NULL, recovered_at INTEGER, duration INTEGER, error TEXT, FOREIGN KEY(monitor_id) REFERENCES monitors(id)); CREATE INDEX IF NOT EXISTS checks_monitor_time ON checks(monitor_id, timestamp); CREATE INDEX IF NOT EXISTS incidents_monitor_time ON incidents(monitor_id, started_at);`);
  for (const statement of ['ALTER TABLE monitors ADD COLUMN monitor_type TEXT NOT NULL DEFAULT \'http\'', 'ALTER TABLE monitors ADD COLUMN group_name TEXT', 'ALTER TABLE monitors ADD COLUMN heartbeat_token TEXT', 'ALTER TABLE monitors ADD COLUMN expected_interval INTEGER', 'ALTER TABLE monitors ADD COLUMN grace_period INTEGER', 'ALTER TABLE monitors ADD COLUMN last_heartbeat_at INTEGER', 'ALTER TABLE monitors ADD COLUMN domain_expiration_date INTEGER', 'ALTER TABLE monitors ADD COLUMN domain_days_remaining INTEGER', 'ALTER TABLE monitors ADD COLUMN warning_threshold INTEGER NOT NULL DEFAULT 30', 'ALTER TABLE monitors ADD COLUMN warning_alerted INTEGER NOT NULL DEFAULT 0', 'ALTER TABLE monitors ADD COLUMN udp_payload TEXT', 'ALTER TABLE monitors ADD COLUMN udp_expected_response TEXT', 'ALTER TABLE monitors ADD COLUMN failure_threshold INTEGER NOT NULL DEFAULT 2', 'ALTER TABLE monitors ADD COLUMN recovery_notifications INTEGER NOT NULL DEFAULT 1', 'ALTER TABLE monitors ADD COLUMN repeat_notification_minutes INTEGER NOT NULL DEFAULT 0', 'ALTER TABLE monitors ADD COLUMN notifications_enabled INTEGER NOT NULL DEFAULT 1', 'ALTER TABLE monitors ADD COLUMN max_latency INTEGER', 'ALTER TABLE monitors ADD COLUMN method TEXT NOT NULL DEFAULT \'GET\'', 'ALTER TABLE monitors ADD COLUMN headers_json TEXT', 'ALTER TABLE monitors ADD COLUMN body TEXT', 'ALTER TABLE monitors ADD COLUMN json_path TEXT', 'ALTER TABLE monitors ADD COLUMN json_expected TEXT', 'ALTER TABLE monitors ADD COLUMN active INTEGER NOT NULL DEFAULT 1', 'ALTER TABLE monitors ADD COLUMN maintenance INTEGER NOT NULL DEFAULT 0', 'ALTER TABLE monitors ADD COLUMN slow_alerted INTEGER NOT NULL DEFAULT 0', 'ALTER TABLE monitors ADD COLUMN ssl_alerted INTEGER NOT NULL DEFAULT 0', 'ALTER TABLE monitors ADD COLUMN ssl_valid INTEGER', 'ALTER TABLE monitors ADD COLUMN ssl_expires_at INTEGER', 'ALTER TABLE monitors ADD COLUMN ssl_days_remaining INTEGER', 'ALTER TABLE checks ADD COLUMN slow INTEGER NOT NULL DEFAULT 0', 'ALTER TABLE incidents ADD COLUMN last_notified_at INTEGER', 'ALTER TABLE incidents ADD COLUMN notification_count INTEGER NOT NULL DEFAULT 0']) { try { db.exec(statement); } catch { /* Existing installations already have this column. */ } }
  return db;
}
export function monitorCount(db: Database.Database) { return (db.prepare('SELECT COUNT(*) as count FROM monitors').get() as {count:number}).count; }
export function syncMonitors(db: Database.Database, monitors: MonitorConfig[]) { const now = Date.now(); const stmt = db.prepare(`INSERT INTO monitors (id,name,url,monitor_type,group_name,heartbeat_token,expected_interval,grace_period,interval,timeout,expected_status,keyword,max_latency,method,headers_json,body,json_path,json_expected,active,created_at) VALUES (@id,@name,@url,@type,@group,@token,@expectedInterval,@gracePeriod,@interval,@timeout,@expectedStatus,@keyword,@maxLatency,@method,@headers,@body,@jsonPath,@jsonExpected,@active,@now) ON CONFLICT(id) DO UPDATE SET name=@name,url=@url,monitor_type=@type,group_name=@group,expected_interval=@expectedInterval,grace_period=@gracePeriod,interval=@interval,timeout=@timeout,expected_status=@expectedStatus,keyword=@keyword,max_latency=@maxLatency,method=@method,headers_json=@headers,body=@body,json_path=@jsonPath,json_expected=@jsonExpected`); db.transaction(() => monitors.forEach(m => stmt.run({...m, type:m.type ?? 'http', group:m.group ?? null, token:null, expectedInterval:m.expectedInterval ?? null, gracePeriod:m.gracePeriod ?? null, keyword:m.keyword ?? null, maxLatency:m.maxLatency ?? null, method:m.method ?? 'GET', headers:m.headers ? JSON.stringify(m.headers) : null, body:m.body ?? null, jsonPath:m.jsonPath ?? null, jsonExpected:m.jsonExpected ?? null, active:m.active === false ? 0 : 1, now})))(); }
const selectMonitor = 'SELECT id,name,url,COALESCE(monitor_type,\'http\') as type,group_name as groupName,heartbeat_token as heartbeatToken,expected_interval as expectedInterval,grace_period as gracePeriod,last_heartbeat_at as lastHeartbeatAt,domain_expiration_date as domainExpirationDate,domain_days_remaining as domainDaysRemaining,warning_threshold as warningThreshold,warning_alerted as warningAlerted,udp_payload as udpPayload,udp_expected_response as udpExpectedResponse,failure_threshold as failureThreshold,recovery_notifications as recoveryNotifications,repeat_notification_minutes as repeatNotificationMinutes,notifications_enabled as notificationsEnabled,interval,timeout,expected_status as expectedStatus,keyword,max_latency as maxLatency,method,headers_json as headersJson,body,json_path as jsonPath,json_expected as jsonExpected,active,maintenance,slow_alerted as slowAlerted,ssl_alerted as sslAlerted,state,outage_started as outageStarted,consecutive_failures as consecutiveFailures,ssl_valid as sslValid,ssl_expires_at as sslExpiresAt,ssl_days_remaining as sslDaysRemaining,created_at as createdAt FROM monitors';
export function getMonitor(db: Database.Database, id: string): MonitorRow | undefined { const row = db.prepare(`${selectMonitor} WHERE id=?`).get(id) as any; return row ? {...row, group:row.groupName, active: Boolean(row.active), maintenance:Boolean(row.maintenance), slowAlerted:Boolean(row.slowAlerted), sslAlerted:Boolean(row.sslAlerted), warningAlerted:Boolean(row.warningAlerted), failureThreshold:Number(row.failureThreshold??2), recoveryNotifications:row.recoveryNotifications!==0, notificationsEnabled:row.notificationsEnabled!==0, headers:row.headersJson ? JSON.parse(row.headersJson) : undefined, sslValid: row.sslValid === null ? null : Boolean(row.sslValid)} : undefined; }
export function findHeartbeatByToken(db: Database.Database, token: string): MonitorRow | undefined { const row=db.prepare(`${selectMonitor} WHERE heartbeat_token=? AND monitor_type='heartbeat'`).get(token) as any; return row ? {...row,group:row.groupName,active:Boolean(row.active),maintenance:Boolean(row.maintenance),slowAlerted:Boolean(row.slowAlerted),sslAlerted:Boolean(row.sslAlerted),headers:undefined,sslValid:row.sslValid===null?null:Boolean(row.sslValid)} : undefined; }
export function heartbeatUrl(db: Database.Database,id:string,base:string) { const row=db.prepare('SELECT heartbeat_token as token FROM monitors WHERE id=? AND monitor_type=\'heartbeat\'').get(id) as {token?:string}|undefined; return row?.token ? `${base.replace(/\/$/,'')}/api/heartbeat/${row.token}` : undefined; }
export function listMonitors(db: Database.Database, activeOnly = false): MonitorRow[] { return db.prepare(`${selectMonitor}${activeOnly ? ' WHERE active=1' : ''} ORDER BY name`).all().map((row:any) => ({...row, group:row.groupName, active:Boolean(row.active), maintenance:Boolean(row.maintenance), slowAlerted:Boolean(row.slowAlerted), sslAlerted:Boolean(row.sslAlerted), warningAlerted:Boolean(row.warningAlerted), failureThreshold:Number(row.failureThreshold??2), recoveryNotifications:row.recoveryNotifications!==0, notificationsEnabled:row.notificationsEnabled!==0, headers:row.headersJson ? JSON.parse(row.headersJson) : undefined, sslValid:row.sslValid===null?null:Boolean(row.sslValid)})); }
export function saveMonitor(db: Database.Database, monitor: MonitorConfig) { const now=Date.now(); const existing=getMonitor(db,monitor.id); const token=monitor.type==='heartbeat' ? existing?.heartbeatToken ?? randomUUID().replace(/-/g,'') : null; db.prepare(`INSERT INTO monitors (id,name,url,monitor_type,group_name,heartbeat_token,expected_interval,grace_period,warning_threshold,interval,timeout,expected_status,keyword,max_latency,method,headers_json,body,json_path,json_expected,active,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,url=excluded.url,monitor_type=excluded.monitor_type,group_name=excluded.group_name,heartbeat_token=excluded.heartbeat_token,expected_interval=excluded.expected_interval,grace_period=excluded.grace_period,warning_threshold=excluded.warning_threshold,interval=excluded.interval,timeout=excluded.timeout,expected_status=excluded.expected_status,keyword=excluded.keyword,max_latency=excluded.max_latency,method=excluded.method,headers_json=excluded.headers_json,body=excluded.body,json_path=excluded.json_path,json_expected=excluded.json_expected,active=excluded.active`).run(monitor.id,monitor.name,monitor.url,monitor.type ?? 'http',monitor.group ?? null,token,monitor.expectedInterval ?? null,monitor.gracePeriod ?? null,monitor.warningThreshold ?? 30,monitor.interval,monitor.timeout,monitor.expectedStatus,monitor.keyword ?? null,monitor.maxLatency ?? null,monitor.method ?? 'GET',monitor.headers ? JSON.stringify(monitor.headers) : null,monitor.body ?? null,monitor.jsonPath ?? null,monitor.jsonExpected ?? null,monitor.active === false ? 0 : 1,now); if(monitor.type==='udp') setUdpConfig(db,monitor.id,monitor.udpPayload,monitor.udpExpectedResponse); if(monitor.failureThreshold!==undefined||monitor.recoveryNotifications!==undefined||monitor.repeatNotificationMinutes!==undefined||monitor.notificationsEnabled!==undefined) setNotificationConfig(db,monitor.id,monitor); return getMonitor(db,monitor.id)!; }
export function newMonitor(db: Database.Database, monitor: Omit<MonitorConfig,'id'>) { return saveMonitor(db,{...monitor,id:randomUUID()}); }
export function removeMonitor(db: Database.Database, id: string) { db.transaction(() => { db.prepare('DELETE FROM checks WHERE monitor_id=?').run(id); db.prepare('DELETE FROM incidents WHERE monitor_id=?').run(id); db.prepare('DELETE FROM monitors WHERE id=?').run(id); })(); }
export function setMonitorActive(db: Database.Database, id: string, active: boolean) { db.prepare('UPDATE monitors SET active=? WHERE id=?').run(active ? 1 : 0,id); return getMonitor(db,id); }
export function setMaintenance(db: Database.Database, id: string, maintenance: boolean) { db.prepare('UPDATE monitors SET maintenance=? WHERE id=?').run(maintenance ? 1 : 0,id); return getMonitor(db,id); }
export function setDomainConfig(db: Database.Database,id:string,warningThreshold:number) { db.prepare('UPDATE monitors SET warning_threshold=? WHERE id=?').run(warningThreshold,id); return getMonitor(db,id); }
export function setUdpConfig(db: Database.Database,id:string,payload:string|undefined,expectedResponse:string|undefined) { db.prepare('UPDATE monitors SET udp_payload=?,udp_expected_response=? WHERE id=?').run(payload??null,expectedResponse??null,id); return getMonitor(db,id); }
export function setNotificationConfig(db: Database.Database,id:string,config:Pick<MonitorConfig,'failureThreshold'|'recoveryNotifications'|'repeatNotificationMinutes'|'notificationsEnabled'>) { db.prepare('UPDATE monitors SET failure_threshold=?,recovery_notifications=?,repeat_notification_minutes=?,notifications_enabled=? WHERE id=?').run(config.failureThreshold??2,config.recoveryNotifications===false?0:1,config.repeatNotificationMinutes??0,config.notificationsEnabled===false?0:1,id); return getMonitor(db,id); }
export function logNotification(db: Database.Database,monitorId:string,incidentId:number|undefined,eventType:string,provider:string,success:boolean,error?:string,at=Date.now()) { db.prepare('INSERT INTO notification_history (monitor_id,incident_id,event_type,provider,sent_at,success,error) VALUES (?,?,?,?,?,?,?)').run(monitorId,incidentId??null,eventType,provider,at,success?1:0,error??null); }
export function markIncidentNotified(db: Database.Database,incidentId:number,at=Date.now()) { db.prepare('UPDATE incidents SET last_notified_at=?,notification_count=notification_count+1 WHERE id=?').run(at,incidentId); }
export function notificationHistory(db: Database.Database,monitorId?:string) { return db.prepare(`SELECT id,monitor_id as monitorId,incident_id as incidentId,event_type as eventType,provider,sent_at as sentAt,success,error FROM notification_history${monitorId?' WHERE monitor_id=?':''} ORDER BY sent_at DESC LIMIT 100`).all(...(monitorId?[monitorId]:[])); }
export function repeatIncidents(db: Database.Database,now=Date.now()) { return db.prepare(`SELECT i.id as incidentId,i.monitor_id as monitorId,m.name,m.url,m.state,m.repeat_notification_minutes as repeatMinutes,i.started_at as startedAt,i.last_notified_at as lastNotifiedAt FROM incidents i JOIN monitors m ON m.id=i.monitor_id WHERE i.recovered_at IS NULL AND m.active=1 AND m.maintenance=0 AND m.notifications_enabled=1 AND m.repeat_notification_minutes>0 AND i.last_notified_at IS NOT NULL AND ?-i.last_notified_at >= m.repeat_notification_minutes*60000`).all(now) as any[]; }
export function recordDomainResult(db: Database.Database, monitor: MonitorConfig, result: DomainResult, at=Date.now()) { const current=getMonitor(db,monitor.id); if(!current) throw new Error(`Unknown monitor ${monitor.id}`); const failed=result.status==='DOWN'; const failures=failed?current.consecutiveFailures+1:0; const threshold=monitor.failureThreshold??current.failureThreshold??2; let state=current.state; let outageStarted=current.outageStarted; let incidentId:number|undefined; if(failed&&failures>=threshold&&state==='UP'){state='DOWN';outageStarted=at;incidentId=Number(db.prepare('INSERT INTO incidents (monitor_id,started_at,error) VALUES (?,?,?)').run(monitor.id,at,result.error??'Domain expiration lookup failed').lastInsertRowid);} const recovered=!failed&&state==='DOWN'; if(recovered){state='UP';db.prepare('UPDATE incidents SET recovered_at=?,duration=? WHERE monitor_id=? AND recovered_at IS NULL').run(at,at-(outageStarted??at),monitor.id);} const warning=result.warning&&!current.warningAlerted; db.prepare('UPDATE monitors SET domain_expiration_date=?,domain_days_remaining=?,warning_alerted=?,state=?,outage_started=?,consecutive_failures=? WHERE id=?').run(result.expirationDate,result.daysRemaining,result.warning?1:0,state,state==='DOWN'?outageStarted:null,failures,monitor.id); return {state,recovered,transitionedDown:current.state==='UP'&&state==='DOWN',outageStarted:current.outageStarted,warning,incidentId}; }
export function receiveHeartbeat(db: Database.Database, token: string, at=Date.now()) { const current=findHeartbeatByToken(db,token); if (!current || !current.active) return undefined; const recovered=current.state==='DOWN'; if (recovered) db.prepare('UPDATE incidents SET recovered_at=?,duration=? WHERE monitor_id=? AND recovered_at IS NULL').run(at,at-(current.outageStarted ?? at),current.id); db.prepare('UPDATE monitors SET last_heartbeat_at=?,state=?,outage_started=?,consecutive_failures=0 WHERE id=?').run(at,'UP',null,current.id); return {monitor: getMonitor(db,current.id)!, recovered, outageStarted: current.outageStarted}; }
export function evaluateHeartbeats(db: Database.Database, now=Date.now()) { const due=db.prepare(`SELECT id FROM monitors WHERE monitor_type='heartbeat' AND active=1 AND maintenance=0 AND (? > COALESCE(last_heartbeat_at,created_at) + (expected_interval + grace_period) * 1000) AND state='UP'`).all(now) as {id:string}[]; return due.map(({id})=>{const current=getMonitor(db,id)!; db.prepare('UPDATE monitors SET state=\'DOWN\',outage_started=?,consecutive_failures=? WHERE id=?').run(now,current.failureThreshold??2,id); const incidentId=Number(db.prepare('INSERT INTO incidents (monitor_id,started_at,error) VALUES (?,?,?)').run(id,now,'Heartbeat missed its expected interval').lastInsertRowid); return {monitor:getMonitor(db,id)!,outageStarted:now,incidentId};}); }
export function recordCheck(db: Database.Database, monitor: MonitorConfig, result: CheckResult, at = Date.now()) {
  const current=getMonitor(db,monitor.id); if (!current) throw new Error(`Unknown monitor ${monitor.id}`); const failures=result.status==='DOWN' ? current.consecutiveFailures+1 : 0; const threshold=monitor.failureThreshold ?? current.failureThreshold ?? 2; let state=current.state, outageStarted=current.outageStarted; let incidentId:number|undefined;
  if (result.status==='DOWN' && failures>=threshold && state==='UP') { state='DOWN'; outageStarted=at; incidentId=Number(db.prepare('INSERT INTO incidents (monitor_id,started_at,error) VALUES (?,?,?)').run(monitor.id,at,result.error ?? null).lastInsertRowid); }
  const recovered=result.status==='UP' && state==='DOWN'; const previousOutage=current.outageStarted;
  if (recovered) { state='UP'; db.prepare('UPDATE incidents SET recovered_at=?,duration=? WHERE monitor_id=? AND recovered_at IS NULL').run(at,at-(previousOutage ?? at),monitor.id); }
  const previousCheck=db.prepare('SELECT slow FROM checks WHERE monitor_id=? ORDER BY timestamp DESC LIMIT 1').get(monitor.id) as {slow:number}|undefined;
  const slowAlert=Boolean(result.slow)&&!Boolean(previousCheck?.slow); const sslThreshold=Number(process.env.SSL_EXPIRY_DAYS ?? 30); const sslAlert=Boolean(result.certificate?.valid && result.certificate.daysRemaining !== null && result.certificate.daysRemaining <= sslThreshold && !current.sslAlerted);
  db.prepare('INSERT INTO checks (monitor_id,timestamp,status,latency,slow,error) VALUES (?,?,?,?,?,?)').run(monitor.id,at,result.status,result.latency,result.slow ? 1 : 0,result.error ?? null);
  if (result.certificate) db.prepare('UPDATE monitors SET ssl_valid=?,ssl_expires_at=?,ssl_days_remaining=?,slow_alerted=?,ssl_alerted=? WHERE id=?').run(result.certificate.valid ? 1 : 0,result.certificate.expiresAt,result.certificate.daysRemaining, result.slow ? 1 : 0, sslAlert ? 1 : 0, monitor.id);
  else db.prepare('UPDATE monitors SET slow_alerted=? WHERE id=?').run(result.slow ? 1 : 0,monitor.id);
  db.prepare('UPDATE monitors SET state=?,outage_started=?,consecutive_failures=? WHERE id=?').run(state,state==='DOWN' ? outageStarted : null,failures,monitor.id);
  return { previousState:current.state,state,transitionedDown:current.state==='UP'&&state==='DOWN',recovered,outageStarted:previousOutage,slowAlert,sslAlert,incidentId };
}
export function cleanup(db: Database.Database, now=Date.now()) { const cutoff=now-90*86400000; const checks=db.prepare('DELETE FROM checks WHERE timestamp < ?').run(cutoff).changes; const incidents=db.prepare('DELETE FROM incidents WHERE started_at < ?').run(cutoff).changes; return checks+incidents; }
export async function backupDatabase(db: Database.Database, directory: string) { fs.mkdirSync(directory,{recursive:true}); const filename=path.join(directory,`uptime-${new Date().toISOString().replace(/[:.]/g,'-')}.db`); await db.backup(filename); return filename; }
export function uptime(db: Database.Database,id:string,since:number,now=Date.now()) { const row=db.prepare(`SELECT COALESCE(SUM(CASE WHEN status='UP' THEN 1 ELSE 0 END),0) as up,COUNT(*) as total FROM checks WHERE monitor_id=? AND timestamp>=? AND timestamp<=?`).get(id,since,now) as any; return row.total ? (row.up/row.total)*100 : 100; }
export function incidents(db: Database.Database,id?:string): Incident[] { return db.prepare(`SELECT id,monitor_id as monitorId,started_at as startedAt,recovered_at as recoveredAt,duration,error FROM incidents${id ? ' WHERE monitor_id=?' : ''} ORDER BY started_at DESC LIMIT 50`).all(...(id ? [id] : [])) as Incident[]; }
export function dashboardData(db: Database.Database, publicView=false) { return listMonitors(db,publicView).map(m => { const {heartbeatToken: _secret, ...safe}=m; const latest=db.prepare('SELECT timestamp,latency,status,slow FROM checks WHERE monitor_id=? ORDER BY timestamp DESC LIMIT 1').get(m.id) as any; return {...safe, latestLatency:latest?.latency ?? null,lastChecked:latest?.timestamp ?? null,latestSlow:Boolean(latest?.slow),uptime24h:uptime(db,m.id,Date.now()-86400000),uptime7d:uptime(db,m.id,Date.now()-7*86400000),uptime30d:uptime(db,m.id,Date.now()-30*86400000),history:db.prepare('SELECT timestamp,latency,status,slow FROM checks WHERE monitor_id=? ORDER BY timestamp DESC LIMIT 30').all(m.id).reverse(),incidents:incidents(db,m.id),notificationHistory:publicView?undefined:notificationHistory(db,m.id)}; }); }
